# Generated by Django 4.2.9 on 2024-01-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart_food',
            name='number_food',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
