# Generated by Django 4.2.9 on 2024-01-24 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_discount_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='foods_like',
            field=models.ManyToManyField(blank=True, null=True, to='api.food'),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='restaurant_like',
            field=models.ManyToManyField(blank=True, null=True, to='api.restaurant'),
        ),
    ]
