# Generated by Django 4.2.9 on 2024-01-18 14:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_myuser_birthdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='rate',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
