# Generated by Django 4.2.9 on 2024-01-24 23:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cart_food_number_food'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='foods',
        ),
        migrations.CreateModel(
            name='Cart_Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.cart')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant')),
            ],
        ),
    ]
