# Generated by Django 4.2.9 on 2024-01-18 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_restaurant_rate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='rastaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(to='api.food'),
        ),
    ]
