# Generated by Django 4.2.9 on 2024-01-24 21:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_myuser_foods_like_alter_myuser_restaurant_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pr', 'Processing'), ('ca', 'Cancel'), ('co', 'Complete')], default='pr', max_length=2),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_discription',
            field=models.TextField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='cart',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
