# Generated by Django 4.2.9 on 2024-01-25 00:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_cart_foods_cart_restaurant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.restaurant'),
        ),
    ]
