# Generated by Django 4.2.9 on 2024-01-25 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_cart_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='address_delivery',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.address'),
        ),
    ]
