# Generated by Django 4.2.9 on 2024-01-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_food_rastaurant_restaurant_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(blank=True, to='api.food'),
        ),
    ]
