# Generated by Django 4.2.9 on 2024-01-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_restaurant_foods'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='foods',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='api.food'),
        ),
    ]
